apiVersion: v1
kind: Service
metadata:
  name: veraks-redis
  labels:
    {{- include "veraks.labels" . | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/name: veraks
    veraks/component: redis
  ports:
    - port: 6379
      targetPort: 6379
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: veraks-redis
  labels:
    {{- include "veraks.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: veraks
      veraks/component: redis
  template:
    metadata:
      labels:
        app.kubernetes.io/name: veraks
        veraks/component: redis
    spec:
      containers:
        - name: redis
          image: "{{ .Values.images.redis.repository }}:{{ .Values.images.redis.tag }}"
          ports:
            - containerPort: 6379
          readinessProbe:
            exec:
              command: ["redis-cli", "ping"]
            initialDelaySeconds: 3
            periodSeconds: 5
          resources:
            {{- toYaml .Values.redis.resources | nindent 12 }}
